name       : telepathy-mission-control
version    : 5.16.5
release    : 9
source     :
    - https://telepathy.freedesktop.org/releases/telepathy-mission-control/telepathy-mission-control-5.16.5.tar.gz : 4c6b433b8b9079fd7df3e29aefcad6755a2081a9a634ffb6b33936c7d0d8bd03
license    : LGPL-2.1-only
component  : programming.library
summary    : An account manager and channel dispatcher for the Telepathy framework
description: |
    An account manager and channel dispatcher for the Telepathy framework
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libnm)
    - pkgconfig(libxslt)
    - pkgconfig(telepathy-glib)
    - gtk-doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
