name       : telepathy-mission-control
version    : 5.16.4
release    : 6
source     :
    - http://telepathy.freedesktop.org/releases/telepathy-mission-control/telepathy-mission-control-5.16.4.tar.gz : 9769ddac7ad8aad21f6db854016792162b57e6fa0b0aed8d823d76a71fe7e6cb
license    : LGPL-2.1-only
component  : programming.library
summary    : An account manager and channel dispatcher for the Telepathy framework
description: |
    An account manager and channel dispatcher for the Telepathy framework
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libnm)
    - pkgconfig(libxslt)
    - pkgconfig(python-2.7)
    - pkgconfig(telepathy-glib)
    - gtk-doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
