name       : telepathy-mission-control
version    : 5.16.3
release    : 2
source     :
    - https://telepathy.freedesktop.org/releases/telepathy-mission-control/telepathy-mission-control-5.16.3.tar.gz : 71575d2ff8aa7337aca355e3d921eba5cd2ff050fabc01e51577343093e98b7d
license    : LGPL-2.1
component  : programming
summary    : An account manager and channel dispatcher for the Telepathy framework
description: |
    An account manager and channel dispatcher for the Telepathy framework
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libnm)
    - pkgconfig(libxslt)
    - pkgconfig(python-2.7)
    - pkgconfig(telepathy-glib)
    - gtk-doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
