name       : telepathy-mission-control
version    : 5.16.6
release    : 11
source     :
    - https://telepathy.freedesktop.org/releases/telepathy-mission-control/telepathy-mission-control-5.16.6.tar.gz : 2df8ae3995e919a7670e01aa3568215ef0777e34961ace1cac1c6477cb297a45
license    : LGPL-2.1-only
component  : programming.library
summary    : An account manager and channel dispatcher for the Telepathy framework
description: |
    An account manager and channel dispatcher for the Telepathy framework
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libnm)
    - pkgconfig(libxslt)
    - pkgconfig(telepathy-glib)
    - gtk-doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
